baseURL: https://mattmtong.com
languageCode: en-us
title: "Matt M. Tong"
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  cover:
    linkFullImages: false
  defaultTheme: dark
  disableThemeToggle: false

  disableAnchoredHeadings: false
  ShowBreadCrumbs: true
  ShowFullTextinRSS: true
  ShowReadingTime: true
  comments: true
  ShowWordCount: true
  ShowPostNavLinks: true
  EnableInstantClick: false

  assets:
    favicon: /assets/Logo for Favicon.png
    favicon16x16: /assets/favicon-16x16.png
    favicon32x32: /assets/favicon-32x32.png
    disableScrollBarStyle: true

  label:
    text: "matt m tong "
    icon: /img/logo_bordered.png
    iconheight: 24
  
  editPost:
        URL: "https://github.com/mattmtong/hugo-mattmtong/tree/master/content"
        Text: "View on GitHub" # edit text
        appendFilePath: true # to append file path to Edit link

  homeInfoParams:
    Title: "Hello there, fellow player of life \U0001F579"
    Content: Currently playing piano and cello. Learning to play steno. 

  socialIcons:
  - name: Facebook
    url: "https://www.facebook.com/matt.m.tong/"
  - name: Youtube
    url: "https://www.youtube.com/@mattmtong"
  - name: Instagram
    url: "https://www.instagram.com/mattsouptong/"
  - name: Github
    url: "https://github.com/mattmtong"
  - name: RSS
    url: "https://mattmtong.com/index.xml"

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: about
      name: About
      url: /about/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON 

    