baseURL: https://mattmtong.com
languageCode: en-us
title: "Matthew M. Tong"
theme: PaperMod

params:
  cover:
    linkFullImages: false

  defaultTheme: dark
  disableThemeToggle: false
  disableAnchoredHeadings: true
  ShowBreadCrumbs: true
  ShowFullTextinRSS: true
 

  assets:
    favicon: /assets/Logo for Favicon.png
    favicon16x16: /assets/favicon-16x16.png
    favicon32x32: /assets/favicon-32x32.png
    disableScrollBarStyle: true

  label:
    text: "matt m tong "
    //icon: /img/logo_dark.png
    iconheight: 20
  
  editPost:
        URL: "https://github.com/mattmtong/hugo-mattmtong/tree/master/content"
        Text: "View on GitHub" # edit text
        appendFilePath: true # to append file path to Edit link


 

  ShowReadingTime: true

  comments: true

  homeInfoParams:
    Title: "Hello there, fellow player of life \U0001F579"
    Content: Currently playing piano and cello. Learning to play steno. 

  socialIcons:
  - name: Facebook
    url: "https://www.facebook.com/matt.m.tong/"
  - name: Youtube
    url: "https://www.youtube.com/@mattmtong"
  - name: Instagram
    url: "https://www.instagram.com/mattsouptong/"
  - name: Github
    url: "https://github.com/mattmtong"
  - name: RSS
    url: "https://mattmtong.com/index.xml"

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40
    - identifier: about
      name: About
      url: /about/
      weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON 

    